### ISSUE TITLE
[14.0]Bad requirements duplicate apispec

### ISSUE THREAD

**Issue by flotho** [OCA/rest-framework#96] opened 2021-01-19 09:22 UTC
This part of not accepted when you run a pip install -r  rrquirements : 
https://github.com/OCA/rest-framework/blob/14.0/requirements.txt#L2

@sbidoul @lmignon could you tell me how to change this as it seems to be generated.

Regards

**Comment by sbidoul** [comment] 2021-01-19 09:38
@flotho this should work if you use `pip>=20.3.3`. But yes it should be adapted for consistency.

**Comment by lmignon** [comment] 2021-01-19 09:48
@floho seems to be a bug into the pre-commit hook generating the requirements.txt file. Indeed, apispec is declared twice as dependency into base_rest and base_rest_datamodel.
In base_rest:
```python
    "external_dependencies": {
        "python": [
            "cerberus",
            "pyquerystring",
            "parse-accept-language",
            "apispec>=4.0.0",
        ]
    },
``` 
and in base_rest_datamodel
```
 "external_dependencies": {"python": ["apispec"]},
```

If we modify the external_dependencies into base_res_datamodel, I'm pretty sure the problem will disappear but IMO it's not the right fix.

**Comment by sbidoul** [comment] 2021-01-19 10:00
@lmignon it is not a bug: I consciously decided to not attempt to merge the version specifiers in the `requirements.txt` generator, because the new pip resolver does it automatically. So if it causes issues in practice until people have upgraded pip, the solution is to align external dependencies in the repo.

**Comment by flotho** [comment] 2021-01-19 10:15
I'll try with latest pip and let you know.

Regards

**Comment by lmignon** [comment] 2021-01-19 10:19
Thank you for the explanation @sbidoul .

**Comment by sbidoul** [comment] 2021-04-03 09:06
@flotho did it work for you after a pip upgrade ?

**Comment by lmignon** [comment] 2021-10-11 11:16
@flotho I close the issue. Feel free to reopen if if the problem still exists

**Closed as completed by lmignon** 2021-10-11 11:16 UTC
