### ISSUE TITLE
[16.0] fast_api_auth_jwt: AuthJwtOdooEnv: Incorrect Environment updated

### ISSUE THREAD

**Issue by jakobfischer93** [OCA/rest-framework#426] opened 2024-04-03 16:56 UTC
## Module
fast_api_auth_jwt

## Describe the bug
When using the `auth_jwt_authenticated_odoo_env` dependency, we get  the following error on routes using that dependency:
```
TypeError: odoo_env() got an unexpected keyword argument 'user'
```

## To Reproduce
**Affected versions**: 16.0

1. Create a route which has the dependency `auth_jwt_authenticated_odoo_env`
2. Access the route which uses that dependency

**Expected behavior**
We expected to get an odoo env with the user set according to the user id strategy.

**Additional context**
We were going to add a custom user id strategy. However, this issue also arises when using the default `static` user id strategy.
Seems to be the same issue as seen in #383.

**Comment by sbidoul** [comment] 2024-04-03 17:31
Thanks for reporting. Closing as duplicate of #406

**Closed as completed by sbidoul** 2024-04-03 17:31 UTC
Labels: bug
