### ISSUE TITLE
Minimal Module for RESTful API

### ISSUE THREAD

**Issue by MrTob** [OCA/rest-framework#289] opened 2022-09-26 13:36 UTC
I need help because I can not deal with the documentation

## Module
Base Module

## Problem:
Dear repo contributors,
could any of you give me a little insight into the module.
My requirements are:

- Authentication using username and password 
- or API Key, whichever is easier to implement
- search for specific fields in a model

My Questions are?
-  which modules need to be installed?
- Is base_rest_pydantic needed?
- What is the best practice to develop new endpoints?

Can anyone provide a small demo-project which covers all the bullet-points?
Thanks

**Comment by marcos-mendez** [comment] 2022-09-26 13:52
@MrTob recomend you closing this issue and starting a new tread in our Discord channel. 

https://discord.com/invite/tNby4ku

This is not a bug. 

Marcos

**Closed as completed** 2022-09-26 17:40 UTC
Labels: bug
